# ansible/join.yml

- name: Join worker nodes to Kubernetes cluster
  hosts: kubernetes_nodes
  become: true
  gather_facts: false
  tasks:
    - name: Run join.sh script
      script: ../terraform/join.sh